{% set python_min = "3.8" %}
{% set name = "datapi" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datapi-{{ version }}.tar.gz
  sha256: d0e47035146beb64185c25a84b5061e1d9f3263d46ae988d06466cf6c13726d5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - attrs
    - multiurl >=0.3.2
    - requests
    - typing_extensions

test:
  imports:
    - datapi
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ecmwf-projects/datapi
  summary: ESEE Data Stores API Python Client
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - malmans2
